### ISSUE TITLE
Crontab for Handlers

### ISSUE THREAD

**Issue by yUnoSTAHP** [Roemer/NetDist#4]
It seems like the crontab expression for handlers works only once.

**Comment by Roemer** [comment]
Works here, please verify!

**Comment by yUnoSTAHP** [comment]
Steps to reproduce:
1) Start Server (AutoStart)
2) Start Client
3) Wait until Crontab was triggered a few times (just to see that it works usualy)
4) Stop the Server (caution you need to catch an exception here - see below) 
5) Start the server
6) Wait until crontab triggers again ... (now you need to wait very long) :sweat_smile: 
=> Even if you start it manually, the "NextStart" date is not refreshed.

Guess: There is an Exception when you stop the server "Attempted to access an unloaded appdomain." which might lead to this issue. I will invastigate this asap.

## ServerBase.cs - line 83

```
        try
        {
            var success = InternalStop();
            if (!success)
            {
                Logger.Error("Failed to stop");
            }
            _handlerManager.TearDown();
            _clientManager.Clear();
        }
        catch (Exception exception)
        {
            Logger.Error(exception, "Failed to stop");
        }
```

**Comment by yUnoSTAHP** [comment]
This might solve the problem (pullrequest in a few days)

![handlermanager](https://cloud.githubusercontent.com/assets/10939219/6668173/44581ab4-cbf1-11e4-9cbe-8a3dc6129ea4.png)

![serverbase](https://cloud.githubusercontent.com/assets/10939219/6668192/717e0d32-cbf1-11e4-9684-e15948a9988e.png)

**Comment by Roemer** [comment]
Fixed with pull request https://github.com/Roemer/NetDist/issues/5
